local component = require("component")
local os = require("os")

local speech = component.speech_box

speech.setVolume(1.0)
speech.setRate(1.0)
speech.setPitch(1.0)
speech.setLanguage("en_US")

speech.say("nine")
os.sleep(1)
speech.say("eight")
os.sleep(1)
speech.say("seven")
os.sleep(1)
speech.say("six")
os.sleep(1)
speech.say("five")
os.sleep(1)
speech.say("four")
os.sleep(1)
speech.say("three")
os.sleep(1)
speech.say("two")
os.sleep(1)
speech.say("one")
